config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  get 'manifesto', to: 'pages#manifesto', as: :manifesto
  resources :representatives, only: [:index, :show] do
    collection do
      get :search
    end
    member do
      post :user_request
    end
    resources :reprensatives_votes, only: [:new, :create]
  end
  resources :laws, only: [:index, :show] do
    member do
      get "for" => "laws#for"
      get "against" => "laws#against"
    end
    resources :comments, only: [:create]
    resources :users_votes, only: [:new, :create]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  VOTE = ["pour", "contre"]
  belongs_to :user
  belongs_to :law
  validates :content, presence: true
  validates :voting_status, inclusion: { in: Comment::VOTE }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.law = Law.find(params[:law_id])
    @law = @comment.law
    @comment.user = current_user
    @comment.save
    redirect_to law_path(@law)
  end

  def for
    @comment = Comment.find(params[:id])
    @comment.update(status: "for")
    redirect_to law_path(@law)
  end

  def against
    @comment = Comment.find(params[:id])
    @comment.update(status: "against")
    redirect_to law_path(@law)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :voting_status)
  end
end

app/views/comments/_downvotes.html.erb
<%= count %>

app/views/comments/_new.html.erb
<div class="header-agora">
  <i class="fas fa-comments"></i>
  <h2 class='ml-30'>Agora</h2>
</div>

<div class="forum w-200">
  <div class="forum-card w-100">
    <div class="title-argument">
      <div class="vote-argument">
        <h3>Arguments <strong>pour</strong></h3>
        <i class="fas fa-vote-yea" id="for_count"></i>
        <span id="upvotes">
          <%= render 'comments/upvotes', count: @upvote_count %>
        </span>
      </div>

      <% if user_signed_in? %>
         <%= link_to for_law_path(@law), class: "like", remote: true do %>
          <div class="btn-like for">
            <i class="far fa-thumbs-up"> </i> je suis <strong>pour</strong>
          </div>
          <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <div class="btn-like for">
            <i class="far fa-thumbs-up"> </i> je suis <strong>pour</strong>
          </div>
          <% end %>
      <% end %>
    </div>

      <div class="comments">
     <% if @law.comments.where(voting_status: "pour").count == 0 %>

        <div class="message">
          <%= image_tag('empty-chat.png', height: '300', width: '300') %>
          <h3 class="mb-2">Il n'y a pas de messages</h3>
          <p class="mb-1"> Vous pouvez poster le premier message !</p>
        </div>
       <% else %>
          <% @law.comments.where(voting_status: "pour").order("comments.created_at desc").each do |comment| %>
          <p class="mb-2 mt-3">
            <%= comment.user.first_name.capitalize %>
            <%= comment.user.last_name.capitalize %>
          </p>
            <i class="far fa-clock"> <%= I18n.l(comment.user.created_at, format: '%d %B %Y - %H:%M', locale: :fr) %> </i>
            <div class="forum-content">
              <%= comment.content %>
            </div>
          <% end %>
        <% end %>
      </div>
   </div>

   <div class="forum-card w-100">

      <div class="title-argument">
        <div class="vote-argument">
          <h3>Arguments <strong>contre</strong></h3>
          <i class="fas fa-vote-yea"></i>
          <span id="downvotes">
            <%= render 'comments/downvotes', count: @downvote_count %>
          </span>
        </div>

        <% if user_signed_in? %>
        <%= link_to against_law_path(@law), class: "like", remote: true do %>
          <div class="btn-like">
            <i class="far fa-thumbs-down"> </i> je suis <strong>contre</strong>
          </div>
        <% end %>
        <% else %>
        <%= link_to new_user_session_path do %>
          <div class="btn-like">
            <i class="far fa-thumbs-down"> </i> je suis <strong>contre</strong>
          </div>
        <% end %>
        <% end %>
      </div>

        <div class="comments">
          <% if @law.comments.where(voting_status: "contre").count == 0 %>
            <div class="message">
              <%= image_tag('empty-chat.png', height: '300', width: '300') %>
              <h3 class="mb-2">Il n'y a pas de messages</h3>
              <p class="mb-1"> Vous pouvez poster le premier message !</p>
            </div>
          <% else %>
           <% @law.comments.where(voting_status: "contre").each do |comment| %>
            <p class="mb-2 mt-3">
            <%= comment.user.first_name.capitalize %>
            <%= comment.user.last_name.capitalize %>
            </p>
              <i class="far fa-clock"> <%= comment.user.created_at.strftime('%d %B %Y - %H:%M')%> </i>
                <div class="forum-content">
                  <%= comment.content %>
                </div>
            <% end %>
          <% end %>
        </div>
   </div>
</div>

<div class="form-login">
  <div class="title-message text-center">
    <i class="fas fa-comment-dots"></i> <h2>Poster un message </h2>
  </div>

    <%= simple_form_for [ @law, @comment ] do |f| %>
      <div class="form-inputs">
        <%= f.input :voting_status,
                    collection: Comment::VOTE,
                    label: "Tu es :",
                    as: :radio_buttons,
                    required: true %>
        <%= f.input :content, label: "Ton message", placeholder: "Ecrivez votre message" %>
      </div>

      <% if user_signed_in? %>
      <div class="form-actions text-center">
        <%= f.submit "Ajouter un commentaire", class: 'btn-blue'%>
      </div>
      <% else %>
      <div class="form-actions text-center">
        <%= link_to "Connecte-toi pour écrir un message!", new_user_session_path, class: 'btn-blue' %>
      </div>
      <% end %>
    <% end %>
</div>

app/views/comments/_upvotes.html.erb
<%= count %>