config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  get 'manifesto', to: 'pages#manifesto', as: :manifesto
  resources :representatives, only: [:index, :show] do
    collection do
      get :search
    end
    member do
      post :user_request
    end
    resources :reprensatives_votes, only: [:new, :create]
  end
  resources :laws, only: [:index, :show] do
    member do
      get "for" => "laws#for"
      get "against" => "laws#against"
    end
    resources :comments, only: [:create]
    resources :users_votes, only: [:new, :create]
  end
end

app/views/shared/_card_law.html.erb
<%= link_to law_path(law) do %>
  <div class="card-law">
    <%= image_tag law.photo, alt: "alttext" %>
    <div class="card-law-infos">
      <div>
        <h4><%= law.title %></h4>
        <p>#<%= law.source %> du <%= I18n.l(law.date, format: '%A, %d %b %Y', locale: :fr) %></p>
        <p><%= law.description %></p>
      </div>
      <div class="card-law-votes">
        <p class="for-votes"><i class="fas fa-thumbs-up"></i> <%= law.get_upvotes.size %></p>
        <p class="against-votes"><i class="fas fa-thumbs-down"></i> <%= law.get_downvotes.size %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_card_representative.html.erb
<%= link_to representative_path(representative) do %>
<div class= "card-rep">
    <img src= "https://www.nosdeputes.fr/depute/photo/<%=representative.slug%>/200" />
    <h4><%=representative.last_name%></h4>
    <h4><%=representative.first_name%></h4>
    <p><%=representative.party_acronym %></p>
</div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>Citizens Can®, designed at Le Wagon Paris</p>
</div>

app/views/shared/_grid_show_representatives.erb
  <div class="grid-depute">
    <div class="card-depute-photo">
      <div class= "card-show-representative">
        <div class="d-flex flex-column justify-content-center align-items-center pt-3">
          <%= image_tag "https://www.nosdeputes.fr/depute/photo/#{@representative.slug}/250", alt: "Photo député", width: 150, class: "img-photo" %>
          <h3 class="pt-0 mt-2 black"><%= @name %></h3>
            <p class="mb-0 mt-1 black"><%= @representative.party_acronym %></p>
            <p class="mb-0 mt-1 black">
              <%= @representative.district_num %>
              <% if @representative.district_num == 1  %>
              ère
              <% elsif @representative.district_num == 2 %>
              nd
              <% else %>
              ème
              <% end %>
              circonscription - <%= @representative.department_name %></p>
        </div>
        <div class="d-flex flex-column justify-content-start text-left pl-3 mt-4">
          <div class="d-flex">
            <p  class="mt-0 mb-0 mr-1">Place dans l'hémicycle :</p>
            <p class="mt-0 mb-0 black"> N°<%= @representative.seat_number %></p> 
          </div>
          <div class="d-flex">
            <p class="mt-0 mb-0 mr-1">Nombre de mandats cumulés :  </p>
            <p class="mt-0 mb-0 black"> <%= @depute_nb_mandats %></p>
          </div>
        </div>
        <a class="black my-4 d-block text-left pl-3" href=""><i class="fas fa-search mr-2"></i>Lire la déclaration d'intérêt</a>
        <div class="d-flex flex-column text-left mt-4 pl-3">
          <p class="m-0 black pb-2">Collaborateurs</p>
          <ul>
            <li><p><%= @representative.collaborators[0]  %></p></li>
            <li><p><%= @representative.collaborators[1]  %></p></li>
            <li><p><%= @representative.collaborators[2]  %></p></li>
            <li><p><%= @representative.collaborators[3]  %></p></li>
            <li><p><%= @representative.collaborators[4]  %></p></li>
            <li><p><%= @representative.collaborators[5] %></p></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="stats-important">
      <div class="card-show-representative align-items-center">
        <div class="d-flex justify-content-between">
          <div class="text-center">
            <h2 class="mb-2 fs-60 "><%= @depute_amendements_proposes %></h2>
            <p>amendements <br> proposés</p>
          </div>
          <div class="text-center">
            <h2 class="mb-2 fs-60"><%= @depute_amendements_signes %></h2>
            <p>amendements <br>signés</p>
          </div>
          <div class="text-center">
            <h2 class="mb-2 fs-60"><%= @depute_questions_ecrites %></h2>
            <p>questions <br> écrites</p>
          </div>
          <div class="text-center">
            <h2 class="mb-2 fs-60"><%= @depute_question_orales %></h2>
            <p>questions <br> orales</p>
          </div>
        </div>
      </div>
    </div>
    <div class="card-presence_an">
      <div class= "card-show-representative d-flex flex-column justify-content-between">
        <div>
          <h4 class="black">Présence dans l'hémicycle</h4>
          <div class="chart">
            <canvas id="myChart" data-presence="<%= @depute_semaines_presence %>" width="200" height="100"></canvas>
            <% pourcentage_presence = @depute_semaines_presence * 100 / 52 %>
          </div>
          <div class="pourcentage">
            <h2 class="dark-grey"><%= pourcentage_presence %>%</h2><p> de présence à l'Assemblée</p>
          </div>
         </div>
          <p class="infos-stats"><I>* Nombre de semaines où le député a été relevé présent dans l'hémicycle sur les 12 derniers mois</I></p>
      </div>
    </div>
    <div class="card-propositions">
    </div>
    <div class="card-amendements-questions">
      <div class= "card-show-representative d-flex flex-column justify-content-between">
        <div>
          <h4>Propositions du député</h4>
          <div>
            <div class="chart">
              <canvas id="myBarChart" data-deposees="<%= @depute_propositions_ecrites %>" data-signees="<%= @depute_propositions_signees %>"></canvas>
            </div>
            <div class="d-flex justify-content-between">
              <div>
                <h2 class="dark-grey"><%= @depute_propositions_ecrites %></h2><p>propositions écrites</p>
              </div>
              <div>
                <h2 class="dark-grey"><%= @depute_propositions_signees %></h2><p>propositions signées</p>
              </div>
            </div>
          </div>
        </div>
          <p class="infos-stats"><I>* Nombre de proposition des 12 derniers mois</I></p>
      </div>
    </div>
    <div class="card-missions">
      <div class= "card-show-representative">
        <div class="d-flex flex-column justify-content-between">
          <h4 class="black">Missions en cours</h4>
          <ul class="text-left mb-0 ml-0">
            <% @infos_perso_depute.first(2).each do |responsabilite| %>
              <li>
                <p>
                  <%= responsabilite["responsabilite"]["organisme"] %>
                  ( <strong><%= responsabilite["responsabilite"]["fonction"].capitalize %></strong> depuis le <I><%= responsabilite["responsabilite"]["debut_fonction"] %></I> ) 
                </p>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="precisions-missions"> 
          <p class="infos-stats"><I>* Toutes les missions encore en cours sur l'année 2021</I></p>
        </div>
      </div>
    </div>
    <div class="contact_container">
      <div class="contact_form flex-column">
        <div class="d-flex justify-content-center mb-5">
          <h4 class="black">Contacte ton député</h4>
        </div>
        <div class="d-flex justify-content-start">
          <div class="information-contact">
            <p><strong>Informations de contact</strong></p>
            <p><i class="fas fa-envelope"></i> <%= @representative.email %></p>
            <p><i class="fas fa-phone-alt"></i> 05 62 68 09 55</p>
          </div>
          <div>
            <p class="margin-b-40"><strong>Envoyer un message à <%= @representative.first_name %> <%= @representative.last_name %></strong></p>
            <%= render 'shared/rep_contact_form' %>
          </div>
        </div>
      </div>
    </div>
</div>
  </div>

app/views/shared/_law_show.html.erb
<div class="general-law">
    <div class="description-law">
      <h2><%= @law.title %></h2>
      <div class="law-author">
        <% if @law.author_type == "auteur" %>
          <p><%= @law.source %> déposée par <%= @law.author%></p>
        <% elsif @law.author_type == "rapporteur" %>
          <p><%= @law.source %>, rapporteur : <%= @law.author%></p>
        <% else %>
        <% end %>
        <a href="<%= @law.url %>" target="_blank"><i class="fas fa-search"></i> Consulter</a>
      </div>
      <p><%= @law.description %>.</p>
    </div>

  <% if current_user %>
   <div class="card-depute">
        <h3 class="mb-3">Interpelle ton député</h3>
        <%= image_tag "https://www.nosdeputes.fr/depute/photo/#{current_user.district.representative.slug}/250", alt: "Photo député", width: 100, class: "avatar-depute" %>
        <p class="m-top-10"> <strong><%= current_user.district.representative.first_name %> <%= current_user.district.representative.last_name %> </p></strong>
        <p class="m-0"> Son parti : <strong><%= current_user.district.representative.party_acronym %></strong> </p>
        <p class="m-0"> Son département : <strong><%= current_user.district.representative.department_name %></strong></p>
        <%= link_to 'Contacter', representative_path(current_user.district.representative), :class => "btn-blue" %>
   </div>
    <% else %>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav>
  <%= link_to "CC", root_path, id: "logo" %>
  <% if current_user %>
      <div class="menu">
        <%= link_to "Manifesto", manifesto_path, class: 'nav-link' %>
        <%= link_to "Lois", laws_path, class: 'nav-link' %>
        <%= link_to "Députés", representatives_path, class: 'nav-link' %>
        <%= image_tag("https://www.fluidogroup.com/wp-content/uploads/2018/09/user-icon-silhouette-ae9ddcaf4a156a47931d5719ecee17b9-400x400.png", input_html: { id: "navbarDropdown" }, data: { toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" }, class: 'avatar dropdown-toggle') %>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <i class="far fa-address-card mr-3"></i><%= link_to "mon député", representative_path(current_user.district.representative), class: 'text-capitalize'%><br>
          <i class="fas fa-sign-out-alt mr-3"></i><%= link_to "déconnection", destroy_user_session_path(@user), method: :delete, class: 'text-capitalize' %>
        </div>
      </div>
  <% else %>
    <div class="menu">
      <%= link_to "Manifesto", manifesto_path, class: 'nav-link' %>
      <%= link_to "Députés", representatives_path, class: 'nav-link' %>
      <%= link_to "Lois", laws_path, class: 'nav-link' %>
      <div class="bar"></div>
      <%= link_to "Sign up", new_user_registration_path, class: 'nav-link' %>
      <%= link_to "Log in", new_user_session_path, class: 'nav-link' %>
    </div>
  <% end %>
</nav>

app/views/shared/_pagination.html.erb
<%#
  This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
  calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").

  The link variable is set to a proc that returns the link tag.
  Usage: link.call( page_number [, text [, extra_attributes_string ]])
-%>
<% link = pagy_link_proc(pagy) -%>
<%#                            -%><nav aria-label="pager" class="pagy_nav pagination" role="navigation">
<% if pagy.prev                -%>  <span class="page prev"><%== link.call(pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"') %></span>
<% else                        -%>  <span class="page prev disabled"><%== pagy_t('pagy.nav.prev') %></span>
<% end                         -%>
<% pagy.series.each do |item| # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36] -%>
<%   if    item.is_a?(Integer) -%>  <span class="page"><%== link.call(item) %></span>
<%   elsif item.is_a?(String)  -%>  <span class="page current"><%= item %></span>
<%   elsif item == :gap        -%>  <span class="page gap"><%== pagy_t('pagy.nav.gap') %></span>
<%   end                       -%>
<% end                         -%>
<% if pagy.next                -%>  <span class="page next"><%== link.call(pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next"') %></span>
<% else                        -%>  <span class="page next disabled"><%== pagy_t('pagy.nav.next') %></span>
<% end                         -%>
<%#                            -%></nav>

app/views/shared/_rep_contact_form.html.erb
<%= form_tag user_request_representative_path(@representative), method: :post do %>
   <%= label_tag(:o, "Objet :") %>
   <%= text_field_tag(:o) %>
    <%= label_tag(:m, "Message :") %>
   <%= text_area_tag(:m) %>
   <%= hidden_field_tag :user, @user.id %>
   <%= submit_tag("Envoyer") %>
<% end %>

app/views/shared/_search_bar_representatives.html.erb
<%= form_tag search_representatives_path, method: :get, class: "search-bar-form" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "searchbar-representatives address-input",
    style: "height: auto;",
    placeholder: "Entrez votre adresse"
  %>
  <%= submit_tag "Chercher", class: "btn-search margin-l-minus-50" %>
<% end %>

app/views/shared/_search_bar_reps_index.html.erb
<%= form_tag representatives_path, class: 'relative', method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "searchbar-laws",
    placeholder: "Entrez un député..."
  %>
  <%= submit_tag "Cherchez", class: "btn-search-laws" %>
<% end %>

app/views/shared/_searchbar_laws.html.erb
<%= form_tag laws_path, class: 'relative', method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "searchbar-laws",
    placeholder: "Entrez un mot-clé ou une loi..."
  %>
  <%= submit_tag "Cherchez", class: "btn-search-laws" %>
<% end %>